platform :ios, '9.0'
inhibit_all_warnings!

def common_pods_for_target
    use_frameworks!
    pod 'ObjectMapper'
    pod 'PINRemoteImage'
end

target 'FeaturedGames' do
  common_pods_for_target
end

target 'FeaturedGamesTests' do
    common_pods_for_target
end
